-- Insert SQL Rules Here 
UPDATE Units
SET Combat = '20'
WHERE Type = 'UNIT_MATHALX_DOUSHIN' AND EXISTS (SELECT Type FROM Technologies WHERE Type = 'TECH_PLASTIC_PRINTING');

UPDATE Buildings
SET BuildingClass = 'BUILDINGCLASS_COURTHOUSE', TradeRouteRecipientBonus = '0', TradeRouteTargetBonus = '0', SpecialistType = 'SPECIALIST_MATHALX_CIVIL_SERVANT', Help = 'TXT_KEY_BUILDING_MATHALX_COMMISSION_HELP_PON', Strategy = 'TXT_KEY_BUILDING_MATHALX_COMMISSION_STRATEGY_PON', GoldMaintenance = '1'
WHERE Type = 'BUILDING_MATHALX_COMMISSION' AND EXISTS (SELECT Type FROM Technologies WHERE Type = 'TECH_PLASTIC_PRINTING');

UPDATE Civilization_BuildingClassOverrides
SET BuildingClassType = 'BUILDINGCLASS_COURTHOUSE'
WHERE CivilizationType = 'CIVILIZATION_MATHALX_INAZUMA' AND EXISTS (SELECT Type FROM Technologies WHERE Type = 'TECH_PLASTIC_PRINTING');

DELETE FROM Building_YieldChanges
WHERE BuildingType = 'BUILDING_MATHALX_COMMISSION' AND YieldType = 'YIELD_GOLD' AND EXISTS (SELECT Type FROM Technologies WHERE Type = 'TECH_PLASTIC_PRINTING');

DELETE FROM Building_YieldModifiers
WHERE BuildingType = 'BUILDING_MATHALX_COMMISSION' AND YieldType = 'YIELD_GOLD' AND EXISTS (SELECT Type FROM Technologies WHERE Type = 'TECH_PLASTIC_PRINTING');

INSERT INTO Building_Councilor_Modifiers
		(BuildingType,	AppointedCouncilors,	ElectedCouncilors,	UnlocksCouncil)
VALUES	('BUILDING_MATHALX_COMMISSION',			1,						0,					0);